import { useState, useRef } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  const inputRef = useRef(); 
  const [shortURL, setShortURL] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    const url = inputRef.current.value;
    // TODO : Peticion a la API
    fetch('/api/shortUrl', {
       'method' : 'POST',
       'headers' : { 
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify({ url })
    }).then((res) => res.json())
    .then( (data) => {
       console.log(data.shortUrl);
       setShortURL(data.shortUrl);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Url Shortener
        </h1>

        <p className={styles.description}>
          Cut your URL
        </p>

        <div className={styles.grid} onSubmit={handleSubmit}>
            <form className={styles.card}>
              <input ref={inputRef}  type="text" className={styles.input} placeholder="url"></input>
              <button className={styles.button}>Short</button>
              <span className={styles.inpu}>
                {shortURL}
              </span>
            </form>
        </div>
      </main>
    </div>
  )
}
